---
- name: "Update /etc/hosts"
  template:
    src:  "{{ item.src | default((item.dest | basename ()) + '.j2')}}"
    dest: "{{ item.dest }}"
  with_items:
    - dest:  "/etc/hosts"
  tags:
    - "hosts"
